updated forget check

diff --git a/templates/chkrestic.sh.erb b/templates/chkrestic.sh.erb
--- a/templates/chkrestic.sh.erb
+++ b/templates/chkrestic.sh.erb
@@ -34,8 +34,10 @@ fi
 # check if last backup is long time ago.
 LAST_BACKUP=`cat /var/log/restic/cron.log.1 /var/log/restic/cron.log 2>/dev/null | grep 'Backup succeeded' | tail -n 1 | awk -F '--' '{print $1}'`
 LAST_BACKUP_FAILED=`cat /var/log/restic/cron.log.1 /var/log/restic/cron.log 2>/dev/null | grep 'Backup failed' | tail -n 1 | awk -F '--' '{print $1}'`
+LAST_FORGET_FAILED=`cat /var/log/restic/cron.log.1 /var/log/restic/cron.log 2>/dev/null | grep 'Backup forget action failed' | tail -n 1 | awk -F '--' '{print $1}'`
 LAST_BACKUP_EPOCH=`date +%s -d "$LAST_BACKUP"`
 LAST_BACKUP_FAILED_EPOCH=`date +%s -d "$LAST_BACKUP_FAILED"`
+LAST_FORGET_FAILED_EPOCH=`date +%s -d "$LAST_FORGET_FAILED"`
 PREV_TIME_BACKUP_WARN=`date +%s -d "$WARNING_LEVEL"`
 PREV_TIME_BACKUP_ERROR=`date +%s -d "$ERROR_LEVEL"`
 
@@ -45,19 +47,30 @@ if [ "$LAST_BACKUP" = "" ]; then
 fi
 
 if [ "$LAST_BACKUP_FAILED_EPOCH" -gt "$LAST_BACKUP_EPOCH" ] && [ "$LAST_BACKUP_FAILED" != "" ]; then
-    echo "ERROR: Last backup ended in failed stat, so backup needed. Last backup was $LAST_BACKUP"
+    echo "ERROR: Last backup ended in failed state, backup needed. Last backup was $LAST_BACKUP"
+    exit 2
+fi
+
+if [ "$LAST_BACKUP_FAILED_EPOCH" -gt "$LAST_BACKUP_EPOCH" ] && [ "$LAST_BACKUP_FAILED" != "" ]; then
+    echo "ERROR: Last backup ended in failed state, backup needed. Last backup was $LAST_BACKUP"
     exit 2
 fi
 
 if [ "$PREV_TIME_BACKUP_ERROR" -gt "$LAST_BACKUP_EPOCH" ]; then
-    echo "ERROR: No backup since $ERROR_LEVEL, so backup needed. Last backup was $LAST_BACKUP"
+    echo "ERROR: No backup since $ERROR_LEVEL, backup needed. Last backup was $LAST_BACKUP"
     exit 2
 fi
 
 if [ "$PREV_TIME_BACKUP_WARN" -gt "$LAST_BACKUP_EPOCH" ]; then
-    echo "WARNING: No backup since $ERROR_LEVEL, so backup needed. Last backup was $LAST_BACKUP"
+    echo "WARNING: No backup since $ERROR_LEVEL, backup needed. Last backup was $LAST_BACKUP"
     exit 1
 fi
+
+if [ "$LAST_FORGET_FAILED_EPOCH" -gt "$LAST_BACKUP_EPOCH" ]; then
+    echo "WARNING: Last backup forget action ended in failed state."
+    exit 1
+fi
+
 
 echo "$(date '+%Y-%m-%d %H:%M:%S') -- last backup was ${LAST_BACKUP} -- Backup is ok"
 exit 0
