added error handling to pgsql script;

diff --git a/templates/pgsqlbackup.sh.erb b/templates/pgsqlbackup.sh.erb
--- a/templates/pgsqlbackup.sh.erb
+++ b/templates/pgsqlbackup.sh.erb
@@ -8,6 +8,11 @@
 USER=<%= scope.lookupvar('restic::pgsqlbackupuser') %>
 DIR=<%= scope.lookupvar('restic::backuprootfolder') %>/pgsql
 PREFIX=pgsql
+
+# Define and Create mysql backup directory if needed
+DIR=<%= scope.lookupvar('restic::backuprootfolder') %>/pgsql
+mkdir -p $DIR
+
 <% if scope.lookupvar('restic::docker') == true -%>
 CMD="docker-compose exec <%= scope.lookupvar('restic::docker_container') %>"
 <% else -%>
@@ -23,6 +28,12 @@ set -o pipefail
 
 <% if scope.lookupvar('restic::pgsqlalldatabases') == true -%>
 ${CMD} "pg_dumpall" -U postgres | gzip -c > ${DIR}/${PREFIX}.gz
+    if [ $? -eq 1 ]
+      then
+        echo "Error detected dumping all progress databases"
+        exit 1
+    fi
+
 <% else -%>
 <% scope.lookupvar('restic::pgsqldatabasearray').each do |db| -%>
 <% if scope.lookupvar('restic::pgsqlprebackupvacuum') == true -%>
@@ -30,10 +41,31 @@ ${CMD} "/usr/bin/psql -d <%=db %> <<EOF
 SET statement_timeout = 0;
 VACUUM ANALYZE;
 EOF" | grep -v "SET"
+    if [ $? -eq 1 ]
+      then
+        echo "Error detected during vacuum"
+        exit 1
+    fi
 <% end -%> 
 ${CMD} "pg_dumpall -g -U postgres > ${DIR}/${PREFIX}_<%=db %>_globals.sql"
+    if [ $? -eq 1 ]
+      then
+        echo "Error detected during globals dump of db: <%=db %>"
+        exit 1
+    fi
 ${CMD} "pg_dump <%=db %> -Fc --schema-only > ${DIR}/${PREFIX}_<%=db %>_schemaonly.dump"
+    if [ $? -eq 1 ]
+      then
+        echo "Error detected during schema dump of db: <%=db %>"
+        exit 1
+    fi
 ${CMD} "pg_dump <%=db %> -Fc > ${DIR}/${PREFIX}_<%=db %>.dump"
+    if [ $? -eq 1 ]
+      then
+        echo "Error detected during dump of db: <%=db %>"
+        exit 1
+    fi
+
 <% end -%> 
 <% end -%>
 
